tentando criar o teste da criação do projeto
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "api.crabteam.controllers.requestsBody.NewProject.getNome()" is null